schools_list = "https://www.lectio.dk/lectio/login_list.aspx?showall=1"
assigment_list = "https://www.lectio.dk/lectio/{{SCHOOL_ID}}/OpgaverElev.aspx?elevid={{STUDENT_ID}}"
login_url = "https://www.lectio.dk/lectio/{{SCHOOL_ID}}/login.aspx?lecafdeling={{BRANCH_ID}}"
picture_url = "https://www.lectio.dk/lectio/{{SCHOOL_ID}}/GetImage.aspx?pictureid={{PICTURE_ID}}"
front_page_url = "https://www.lectio.dk/lectio/{{SCHOOL_ID}}/forside.aspx"