'''
Newest documents

https://www.lectio.dk/lectio/517/DokumentOversigt.aspx?elevid=4789793691
__EVENTTARGET:__Page
__EVENTARGUMENT:TREECLICKED_S4789793691__5 - Folder
s_m_Content_Content_FolderTreeView_ExpandState:nnccnnnnnnnnnnncnnncncncnncnnnnncncncnncnncnnnnnnnnnnncncncnncnnncnnncnccncnccncncnnnnnnnnncncnnnnnn
s_m_Content_Content_FolderTreeView_SelectedNode:s_m_Content_Content_FolderTreeViewt1
s_m_Content_Content_FolderTreeView_PopulateLog:
__VIEWSTATEY_KEY:20131611-154158-62033_000037858710_g1dSGyK4eTkgw4pZDe6pGyb/sak=
__VIEWSTATE:
__VIEWSTATEENCRYPTED:
__LASTFOCUS:
time : 0
__EVENTVALIDATION:Ua/Ze3pT2Ar3mDiiDGw5/thg8OtcEWSCSZ4xY+amtJyIe5SHxc3qlKAgQztoYpyXmT3WqgfWXUqtx+xuTSuog3sMEJUSlD08WiqH4A6z7XTgTqOSyT9kfVqBivi9AIpCvnRVx4jMG6t4VaXvtGT2C8jHgO8BSYoPVNHnIkDF3r0IntFJNplncuo0HkzDJ84GwQ41b6RV3efLlckKwG1/qolVofRfCqbRVLnh5ZcFuXWffsPTC5mcRkXnr4GFOrt1jvX5a4L/TS1IuWoSaOCUB7R1nxddw3EY+75jmfLOWkkO/Gpwsk4CUtmAyLmJDe5xwv2hHteBMDE8FCLZ7iuy90ezw9P2yVGeo8jnbQl6Fekl2W2tucHKy0nMobBjso7Bf2g6NHY4X4f6v4UnT4ekr8CVlOhQR9F4Ai8hHwcxic5+FRcfxJKeOBEpC7jQoLMXZjrFwQvP2VOYprZ4WXOsjKRffRThuCYO166Kw1KGcOCSxzd+ys/Y2DT2UIWZYE1/VziUXMYIRU9Dd4K19Ajgxvx2QYCWdFcMktjZozRH7uaQ9y+ZCZ/TIKdfB0aEF4WgUEg2fJXGNCmfcQZ6imWdvAr777wLIIOe/+mjsIUdvGb6M2i34QPU1ZA4GdKAVbkz
s$m$ChooseTerm$term:2013 - Year
s$m$searchinputfield:
s$m$Content$Content$FolderSelect$ctl03:S4789793691__ - Folder ID
LectioPostbackId:
'''
'''
Own groups->Kemi ol -> Timetable

time:0
__EVENTTARGET:__Page
__EVENTARGUMENT:TREECLICKED_H7371036167__6
__LASTFOCUS:
s_m_Content_Content_FolderTreeView_ExpandState:nnccnnnnnnnnnnncnnncncncnncnnnnncncncnncnncnnnnnnnnnnncncncnncnnncnnncnccncneencncnnnnnnnnncncnnnnnn
s_m_Content_Content_FolderTreeView_SelectedNode:s_m_Content_Content_FolderTreeViewt77
s_m_Content_Content_FolderTreeView_PopulateLog:
__VIEWSTATEX:qgMAAGlpZQgxMDA1NzY4NmlsBGsAZwFrAW1sAmhpaWwIawJlEURva3VtZW50IE92ZXJzaWd0awN9AZtzfh0BAAAAawRnAWsFZRpFbGV2ZW4gQm8gSGFucyBUaG9tc2VuLCAycWRsAmhpZGwCZwJpbAJrBmUDb2ZmbARnAmlkbAJnFWlkbAJnAWlsAmsHcWRnA2lkbAJnAWlkbAJnBWlkbAJnAWlkbBhnBWlsAmsIcWRnB2lsAmsIcWRnCWlsAmsIcGRnC2lpbAhrCX0EBxZZtwEAAABrCnFrCHFrB3FkbARoaWlsAmsHcGRsAmcBaWlsAmsLZQJcIGRkZwFpamRqbgFlAVxuAWUNSDczNzEwMzYxNjdfX34BcWRkZw1pbAJrB3FkZw9paWwCawdwZGwCaGlsAmsMZQtTNDc4OTc5MzY5MWRnEWlpbAJrB3BkbAJoaWwCawxlC1M0Nzg5NzkzNjkxZGcVaWlsAmsNZRYvbGVjdGlvL2ltZy9jbGFzcy5hdXRvZGRnF2lpbAJrC2UHa2VtaS1vbGRkZxlpaWwEawtmawdwZGRnHWlsAmsObABkZx9pcxFpbAprD3FrEGUoSW5nZW4gdGlsZ8OmbmdlbGlnZSBkb2t1bWVudGVyIGkgbWFwcGVuLmsRcGsSaGsTZmRqbAJoZwFsAnMFbAJrB3BkZGRkcwVsAmsHcWRkZGRpbAJnB2cHbAFl9QFNYWNvbS5MZWN0aW8uV2ViLlVJLkxlY3Rpb1RlbXBsYXRlRmllbGRgMVtbTWFjb20uTGVjdGlvLkJ1c2luZXNzT2JqZWN0cy5Eb2N1bWVudC5VSURvY3VtZW50Rm9sZGVySXRlbSwgTWFjb20uTGVjdGlvLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dLCBNYWNvbS5MZWN0aW8uV2ViLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbGRkZGRkZGRkbABkcwBkZGRkZHICZSRzJG0kQ29udGVudCRDb250ZW50JERvY3VtZW50R3JpZFZpZXdpcwxkZGRkZGRuAWUHRHVtbXlJRGRoZGRkZGUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fbAFlInMkbSRDb250ZW50JENvbnRlbnQkRm9sZGVyVHJlZVZpZXcUAAAAE1ZhbGlkYXRlUmVxdWVzdE1vZGULc2VsZm9sZGVyaWQIU3ViVGl0bGUIbGVjdGlvaWQFbXR5cGUKRW50aXR5TmFtZQxhdXRvY29tcGxldGUHVmlzaWJsZQdFbmFibGVkEHNlbGVjdGVkZW50aXR5aWQTSXNEcm9wRG93blBvcHVsYXRlZARUZXh0BVZhbHVlCEltYWdlVXJsC0N1cnJlbnREYXRhC18hRGF0YUJvdW5kDUVtcHR5RGF0YVRleHQUX1JlcXVpcmVzRGF0YUJpbmRpbmcLXyFJdGVtQ291bnQKRGF0YU1lbWJlcgEAAQAAAP////8BAAAAAAAAAAQBAAAAf1N5c3RlbS5Db2xsZWN0aW9ucy5HZW5lcmljLkxpc3RgMVtbU3lzdGVtLk9iamVjdCwgbXNjb3JsaWIsIFZlcnNpb249NC4wLjAuMCwgQ3VsdHVyZT1uZXV0cmFsLCBQdWJsaWNLZXlUb2tlbj1iNzdhNWM1NjE5MzRlMDg5XV0DAAAABl9pdGVtcwVfc2l6ZQhfdmVyc2lvbgUAAAgICQIAAAABAAAAAQAAABACAAAABAAAAAkDAAAADQMMBAAAAEpNYWNvbS5MZWN0aW8uQ29tbW9uLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbAUDAAAAFU1hY29tLkxlY3Rpby5Gb2xkZXJJRAQAAAALX2ZvbGRlclR5cGUJX2VudGl0eWlkCV9mb2xkZXJpZBNfc3BlY2lhbEZvbGRlclZhbHVlBAQDAxdNYWNvbS5MZWN0aW8uRm9sZGVyVHlwZQQAAAAYTWFjb20uTGVjdGlvLkFueUxlY3Rpb0lEBAAAAHlTeXN0ZW0uTnVsbGFibGVgMVtbTWFjb20uTGVjdGlvLkFueUxlY3Rpb0lELCBNYWNvbS5MZWN0aW8uQ29tbW9uLCBWZXJzaW9uPTEuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49bnVsbF1dblN5c3RlbS5OdWxsYWJsZWAxW1tTeXN0ZW0uSW50MzIsIG1zY29ybGliLCBWZXJzaW9uPTQuMC4wLjAsIEN1bHR1cmU9bmV1dHJhbCwgUHVibGljS2V5VG9rZW49Yjc3YTVjNTYxOTM0ZTA4OV1dBAAAAAX7////F01hY29tLkxlY3Rpby5Gb2xkZXJUeXBlAQAAAAd2YWx1ZV9fAAgEAAAAAwAAAAX6////GE1hY29tLkxlY3Rpby5BbnlMZWN0aW9JRAIAAAAFX3R5cGUGX3ZhbHVlBAAZTWFjb20uTGVjdGlvLkxlY3Rpb0lEVHlwZQQAAAAJBAAAAAX5////GU1hY29tLkxlY3Rpby5MZWN0aW9JRFR5cGUBAAAAB3ZhbHVlX18ACAQAAAAEAAAABxZZtwEAAAAKCgvnzgS98yJKfofKqjAaPl/sGfzUww==
__VIEWSTATE:
__VIEWSTATEENCRYPTED:
__EVENTVALIDATION:i0CxB0PPWHor8hITbpEnuggqLGjBe6pxciU4ngWFAWhWG4D3iqi8l/C79WQuxUXLZBTt8NoEVFe3kN84CO3JJQH7VZEJH7ZGaCoHE4umB7wGLhtYsoDUtnhBz17aKWE/J/wpYkM3KMq4RZ2vc0cQlEutzdl5iPJL/24fToIUEUO/7ZOoYnNrF4b3EqBrfGWKAv9Bo7zZrPmEKAWibNi4ChHLI5JRe4a+GIJ4K06lA9i7NGdF21ey3lATZpYQLofA7O6+7Gb+K1C6TTuef3xhgQWzJ9cau4gaQCGxTa+YNDzdzzimvCqvU6n0C0cuhHCMGi5L4WBRs8umTBegG3V5B/a7raeqFAQbNAjgcAk8tsqfP02NuclKSR0LtjuYOkpbuMJV/Wj76mHWRz9NLNcHKg==
s$m$ChooseTerm$term:2013
s$m$searchinputfield:
s$m$Content$Content$FolderSelect$ctl03:H7371036167__
LectioPostbackId:

div#s_m_Content_Content_FolderTreeView


https://www.lectio.dk/lectio/517/DokumentOversigt.aspx?elevid=4789793691&folderid=H*TeamID*_FH*FOLDER_TEAMID*_
/lectio/517/DokumentOversigt.aspx?elevid=4789793691&folderid=S*STUDENT_ID*_FS*STUDENTFOLDER_ID*_

Egne dokumenter - https://www.lectio.dk/lectio/517/DokumentOversigt.aspx?elevid=4789793691
	__EVENTTARGET:__Page
	__EVENTARGUMENT:TREECLICKED_S**Student_ID**__
table#s_m_Content_Content_DocumentGridView_ctl00 -> tr

[0] = checkbox
[1] =
	name = span[title] - "Fulde filnavn: "
[2] = Kommentar
[3] = Edited by
[4] = Edited date
[5] = Size
'''
#!/usr/bin/python
# -*- coding: utf8 -*-

from bs4 import BeautifulSoup as Soup
import urls
import re
import proxy
from datetime import *
import time
from time import mktime
import functions
from pytz import timezone

def documents ( config ):
	cookies = {
		"lecmobile" : "0",
		"ASP.NET_SessionId" : session["ASP.NET_SessionId"],
		"LastLoginUserName" : session["LastLoginUserName"],
		"lectiogsc" : session["lectiogsc"],
		"LectioTicket" : session["LectioTicket"]
	}

	# Insert User-agent headers and the cookie information
	headers = {
		"User-Agent" : "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/32.0.1665.2 Safari/537.36",
		"Content-Type" : "application/x-www-form-urlencoded",
		"Host" : "www.lectio.dk",
		"Origin" : "https://www.lectio.dk",
		"Cookie" : functions.implode(cookies, "{{index}}={{value}}", "; ")
	}

	url = "https://www.lectio.dk/lectio/%s/DokumentOversigt.aspx?elevid=%s" %( str(config["school_id"]), str(config["student_id"]) )

	response = proxy.session.get(url, headers=headers)

	html = response.text

	soup = Soup(html)

	if soup.find("table", attrs={"id" : "s_m_Content_Content_DocumentGridView_ctl00"}) is None:
		return {
			"status" : False,
			"error" : "Data not found"
		}